name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ssssss
        run: |
          git config --global user.name "GitHub Actions"
          git subtree push --prefix frontend/dist origin gh-pages
